### ISSUE TITLE
Soldier able to pick up loot it is not adjacent to

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#991] opened 2020-05-08 19:40 UTC
![20200508153154_1](https://user-images.githubusercontent.com/54481962/81442689-125a5380-9142-11ea-9ff4-30027acc3187.jpg)

Same save file as #990. Templar is able to pick up loot from a dead Shieldbearer a screen away (Templar is near the bottom of the screen here, while loot can be seen at the top)

**Comment by copyrite** [comment] 2023-12-23 16:11
Probably duplicate of #182. Seems to have the Psionic Loot perk in common.

**Closed by copyrite** 2023-12-23 16:11 UTC
Labels: bug, duplicate
