### ISSUE TITLE
Officer Perk "Trial by Fire" doesn't work.

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#800] opened 2019-12-08 15:32 UTC
I've sent squaddies on Missions with an Officer with the "Trial by Fire" Perk.
They don't rank up to Sergeant like it claims.
They don't rank up at all unless through normal channels.

**Comment by pledbrook** [comment] 2019-12-09 07:52
Do you have a reproducible example of this? Trial By Fire has worked for me and this is the first report of it. What other mods are you running with?

**Comment by ansabalirai** [comment] 2019-12-09 17:58
Might be a dumb question but did you actually succeed the mission and was the officer alive after the mission end? Just checking if there was some edge case somewhere, since as Peter said, it has worked for almost everyone so far

**Comment by spankahontis** [comment] 2019-12-17 20:51
Zhang Voicepack 
Japanese Voicepack
More Nations and Names WOTC
Xcom International Voicepack
Evac All WOTC
Capnbubs Accessories WOTC
Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)

Yeah, I've completed the mission successfully and he was alive.
Had a Squaddie and a Corporal on the team and neither was promoted to Sergeant.

**Comment by ansabalirai** [comment] 2019-12-17 20:54
Again, just to clarify that they won't necessarily be promoted all the way to Sergeant, just one rank up. From the way you wrote this, it seems that you expected them to hit Sergeant directly after the mission.

Anyway, do you have a savegame for this?

**Comment by spankahontis** [comment] 2019-12-17 21:06
So they only promote one rank up guarantee every successful mission up to Sergeant?

So a Squaddie would have to have 3 Successful Missions with the Officer to reach Sergeant?

Lost the saves, I'll give it another try and let you know.

**Comment by spankahontis** [comment] 2020-01-03 20:25
I've tested it multiple times now, yeah, you're right.
The Squaddies only rank up once per successful mission until they reach Sergeant.

**Comment by flblanc** [comment] 2020-12-04 21:27
Hi ! I am re-opening this issue because it seems the perk does not work in build 20.1. I have sent a squad of Squaddies with an Officer having Trial by Fire twice, and completed the mission both times. Yet, in both instances no squaddie ranked up (not to Sergeant, neither even to LCPL). Could you please investigate?

**Comment by FlashVanMaster** [comment] 2020-12-05 02:29
I think would be nice if you have safe file to reproduce it. For example, i play with this perk and have no problem

**Comment by nightmaRok** [comment] 2020-12-05 06:15
Same for me, play now in 21.5 build and ability work fine on regular soldiers, Sparks or psi.

**Comment by copyrite** [comment] 2023-12-20 06:48
Not a bug, and the one person's problem is old enough at this point to close this.

**Closed by copyrite** 2023-12-20 06:48 UTC
