### ISSUE TITLE
Boosting infiltration from 135% to 200% (would have been 202.5% without cap) INCREASES number of enemies

### ISSUE THREAD

**Issue by Rollo-Tomasi-git** [long-war-2/lwotc#1452] opened 2021-10-03 08:26 UTC
I had a mission at 135% and LIGHT when infiltration timer ran out. Chose to boost it. That INCREASED the number of enemies on the map, new enemy activity became LIGHT-MODERATE.

After reloading and trying this several times, it seems half the time it stays at same activity level, the other half it is increased (not decreased) one level.

See attached screenshots from before and after boost, as well as savegame.
![BeforeInfiltrationBoost_135percent_Light](https://user-images.githubusercontent.com/77572149/135745864-dbfaae47-bbe1-4d88-854f-269417c090d5.png)
![AfterInfiltrationBoost_200percent_LightModerate](https://user-images.githubusercontent.com/77572149/135745866-10e4ab71-e5c5-4fbc-8c2b-c4ba5a4c32f0.png
[save_Dev-28-2_BoostMissionTo200_EnemyBug.zip](https://github.com/long-war-2/lwotc/files/7272950/save_Dev-28-2_BoostMissionTo200_EnemyBug.zip)
)

**Comment by wdanny69** [comment] 2021-10-19 21:20
not a bug but an actual possibility, dark vip missions can have faceless spawned in the mission but being faceless you don't know about them and are unlisted in the suspected enemy activity. when boosting the possible enemy arrangements change such that when you encountered the one with a higher enemy count, it in turn has less faceless in hiding. the effective enemies are still about the same

**Comment by copyrite** [comment] 2024-03-25 17:06
Closing as explained by wdanny69 above, enemy projections of dark VIP missions like this lib 3 hide the Faceless.

**Closed by copyrite** 2024-03-25 17:06 UTC
Labels: wontfix
