### ISSUE TITLE
Wrong Chosen on assault chosen stronghold

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#476] opened 2019-09-03 09:56 UTC
Think this issue similar to #439. I go at assasin stonghold, but meet warlock, after kill warlock, assasin defeated. Give you saves for tests in geoscape before start mission, on mission before ascension gate, on mission after ascension gate and after killing the chosen. Also after ascension gate, skirmisher at start have fire animation.
[Chosen_stronghold.zip](https://github.com/long-war-2/lwotc/files/3568905/Chosen_stronghold.zip)

![000](https://user-images.githubusercontent.com/51829747/64163143-5f668700-ce49-11e9-90e5-67384dbba131.jpg)

**Comment by pledbrook** [comment] 2019-10-01 18:32
Closing as duplicate of #439

**Closed by pledbrook** 2019-10-01 18:32 UTC
Labels: duplicate
