### ISSUE TITLE
[Beta 5?] Bug with 'Take control of a random opponent'?

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1508] opened 2021-12-19 18:15 UTC
After a successful attempt at a takeover by a specialist, nothing happened. When the specialist also succeeded in a 'full override' of a MEC a few turns later, I was able to take control of two units at once. This is probably not supposed to be like this?

![Bug](https://user-images.githubusercontent.com/87030865/146686048-83f87d60-9d32-454f-bf43-c0bab1faa7f6.jpg)

**Comment by copyrite** [comment] 2023-12-23 17:07
Duplicate of #1056

**Closed by copyrite** 2023-12-23 17:07 UTC
Labels: bug, duplicate
