### ISSUE TITLE
Using First action on my turn, ends my turn 

### ISSUE THREAD

**Issue by illogicalproductions** [long-war-2/lwotc#1364] opened 2021-07-02 13:34 UTC
[sharpshooteractionendsturn.zip](https://github.com/long-war-2/lwotc/files/6754881/sharpshooteractionendsturn.zip)

Retaliation, using my sharpshooter as my first action, is ending my turn.
https://www.twitch.tv/videos/1074343621
1hr22 mark is where it first occurs. i forced a crash, copied save, did it again, happened again.

**Comment by illogicalproductions** [comment] 2021-07-02 13:43
update: its not just his first turn, but doob1es taking an action, ends my turn

**Comment by pledbrook** [comment] 2021-07-10 13:34
Is that zip file a save file? Because the file inside it doesn't start with "save_" and I'm not sure what it's called in the Load Game menu if it is a save.

**Comment by illogicalproductions** [comment] 2021-07-10 13:49
Yes, it was a save file.  Renamed to be descriptive.

**Comment by pledbrook** [comment] 2021-07-10 13:51
Do you remember the name of the save file? Was it an ironman one? If so, do you remember the campaign number? (Should show in the Load Game menu if I remember correctly).

**Comment by illogicalproductions** [comment] 2021-07-10 13:54
save_IRONMAN- Campaign 124

**Comment by pledbrook** [comment] 2021-07-10 14:00
It crashes for me. Do you have an AML profile for it that I can use?

**Comment by illogicalproductions** [comment] 2021-07-10 14:02
[illogicalLongWarAMLProfile.txt](https://github.com/long-war-2/lwotc/files/6795389/illogicalLongWarAMLProfile.txt)

**Comment by illogicalproductions** [comment] 2021-07-10 14:02
Wait - thats the new one, for 27.

**Comment by pledbrook** [comment] 2021-07-13 09:59
I'm afraid this is going to have to go down the priority list. It's not reproducible with the debugger attached, which means it will be a lot more work to figure out the cause. Plus it's an ironman save :smile:

**Comment by pledbrook** [comment] 2021-12-21 10:55
I'm going to close this for now. If it happens repeatedly, we can try to work out a way to diagnose the issue.

**Closed by pledbrook** 2021-12-21 10:55 UTC
Labels: bug, has:save
