### ISSUE TITLE
No drop from hacked enemies

### ISSUE THREAD

**Issue by PodliKirill** [long-war-2/lwotc#466] opened 2019-09-01 21:25 UTC
Save - http://s000.tinyupload.com/download.php?file_id=33787603814960843742&t=3378760381496084374250031

Kill hacked drone by templar - you have no loot. If wait 1 turn and kill after hack effect ends - you'll had loot.

**Comment by Clibanarius** [comment] 2019-09-02 09:25
https://steamcommunity.com/sharedfiles/filedetails/?id=1130134672

Bugfix mod for it, it's a WotC/vanilla XCOM2 bug that was present in LW2 as well. Mod fully compatible with WotC LW2 right now, as I'm using it. You can also work around the bug by just moving a soldier on top of the body; the soldier will crouch down as though to pick up loot, finding nothing. Then the loot will pop out properly when he stands back up, and he'll crouch back down and pick up the dropped loot. It's weird, but just use the mod.

**Comment by copyrite** [comment] 2023-12-24 12:55
Duplicate of #1639.

**Closed by copyrite** 2023-12-24 12:55 UTC
Labels: bug, duplicate
