### ISSUE TITLE
unreachable lewts

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1047] opened 2020-05-27 01:06 UTC
See attached save. Advent has marked a crate that i can't possibly get to. It appears to be on the roof of the building, which is above the maximum height on the map. I had this happen once or twice before. This might be related to the glitch that makes enemies appear visually in the wrong place.
[save_AUTOSAVE- Campaign 12, Mission 64, Turn 11_1.zip](https://github.com/long-war-2/lwotc/files/4685826/save_AUTOSAVE-.Campaign.12.Mission.64.Turn.11_1.zip)

**Comment by Grobobobo** [comment] 2020-09-23 16:36
Duplicate of #568

**Closed by Grobobobo** 2020-09-23 16:36 UTC
