### ISSUE TITLE
Crits on assassin chosen in stronghold

### ISSUE THREAD

**Issue by Arubiano83** [long-war-2/lwotc#1181] opened 2020-12-01 07:10 UTC
[save_Assault crit Chosen.txt](https://github.com/long-war-2/lwotc/files/5620800/save_Assault.crit.Chosen.txt)

**Comment by pledbrook** [comment] 2020-12-01 09:43
Sadly, that save file crashes on load for me.

**Comment by pledbrook** [comment] 2020-12-01 09:59
Do you have a strategy save with the mission infiltrating? I wonder if I could replicate the issue from there.

**Comment by Arubiano83** [comment] 2020-12-01 11:17
[save_Psi rush_1.txt](https://github.com/long-war-2/lwotc/files/5622148/save_Psi.rush_1.txt)

**Comment by copyrite** [comment] 2023-12-19 16:20
Closing because the issue is 3 years old and title/description doesn't explain what the problem is.

**Closed by copyrite** 2023-12-19 16:20 UTC
