### ISSUE TITLE
Ever vigilant may has a bug

### ISSUE THREAD

**Issue by bingo12345** [long-war-2/lwotc#816] opened 2019-12-11 23:41 UTC
Someone in korean xcom community has a bug in which ever vigilant perk triggers pistol overwatch when pistol is equiped on pistol slot after beta 2 patch. I can't test and confirm because i am in military service.

**Comment by pledbrook** [comment] 2019-12-12 14:43
Duplicate of #496.

**Closed by pledbrook** 2019-12-12 14:43 UTC
Labels: duplicate
