### ISSUE TITLE
chosen stronghold

### ISSUE THREAD

**Issue by alexu4326** [long-war-2/lwotc#693] opened 2019-10-19 15:03 UTC
![1](https://user-images.githubusercontent.com/54223830/67147077-1c962c80-f29a-11e9-92ac-b36043ddefc7.jpg)
![2](https://user-images.githubusercontent.com/54223830/67147078-1d2ec300-f29a-11e9-97dc-52da921400d7.jpg)
![3](https://user-images.githubusercontent.com/54223830/67147079-1d2ec300-f29a-11e9-9ab4-3bee7764bdde.jpg)

so like in the screnshoot i was going to kill assasin chosen take templar in squad and go
but surprise there is warlock not assasin home

firsth time i was thinking is my fault , not reading description of mission or something 

but is not my fault :))))

[SaveData.zip](https://github.com/long-war-2/lwotc/files/3746829/SaveData.zip)

**Comment by nightmaRok** [comment] 2019-10-20 09:12
Known bug, fixed in next build close #693

**Comment by pledbrook** [comment] 2019-10-23 07:18
Duplicate of #476

**Closed by pledbrook** 2019-10-23 07:18 UTC
Labels: duplicate
