### ISSUE TITLE
LWOTC Not showing up in launcher

### ISSUE THREAD

**Issue by Attie86** [long-war-2/lwotc#1068] opened 2020-06-16 18:24 UTC
I can't seem to get Long War of the Chosen or X2WOTCCommunityHighlander to show up in the launcher. I know I am putting them in the right files. What's weird is if I put them in the regular Xcom2 > XComGame > Mods folder they show up in the launcher but when I run the game there is not LWOTC button. 
![Files](https://user-images.githubusercontent.com/67020521/84812801-cfeb2880-afc3-11ea-8f31-e8f0dfcecd5e.PNG)

**Comment by Grobobobo** [comment] 2020-06-16 18:33
That's a problem caused by the Firaxis launcher update, use Alternative mod Launcher if possible.

**Comment by Hazzardevil** [comment] 2020-06-19 14:40
I've got the same problem. And it's not showing up in the AML either.
https://i.imgur.com/15ROoaz.png
C:\Games\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods
Just to be sure that's the right location.

**Comment by Grobobobo** [comment] 2020-06-19 18:11
AML requires some paths to set up in order to detect local mods. Settings should look somewhat like this: 
![image](https://user-images.githubusercontent.com/50756826/85167401-0eedd800-b269-11ea-98d9-0304bb449785.png)

**Comment by Hazzardevil** [comment] 2020-06-20 00:54
Thanks! That fixed it.

**Comment by flycloudking** [comment] 2020-06-26 16:43
I have the same issue, how to access this setting interface

**Comment by EnsaisReborn** [comment] 2021-12-05 22:10
Bump... any help from a genius out there? :)

**Comment by copyrite** [comment] 2023-12-19 17:43
Closing as local mods are no longer needed, the mod is on Workshop now.

**Closed by copyrite** 2023-12-19 17:43 UTC
