### ISSUE TITLE
Advent shooting on green alert reaction

### ISSUE THREAD

**Issue by GafrieGithub** [long-war-2/lwotc#1190] opened 2020-12-10 19:29 UTC
[save_Save 42 - GreenAlertShotModless.zip](https://github.com/long-war-2/lwotc/files/5675155/save_Save.42.-.GreenAlertShotModless.zip)

To reproduce it simply end the turn after loading the save.

Advent pod walks into sight of xcom on their turn, while being on green alert (which is indicated by their movement speed and the fact it is their first turn without any noise made before). XCom fires and misses 2 OW shots, and then advent trooper take a shot at templar.

**Comment by wdanny69** [comment] 2024-01-17 16:55
cannot reproduce, soldier goes into overwatch instead. it may have been fixed now

if it persists please provide another reproducible save and a mod list

**Comment by copyrite** [comment] 2024-01-17 17:46
There have also been recent improvements regarding this. Seems good enough to me to close.

**Closed by copyrite** 2024-01-17 17:46 UTC
Labels: bug
