### ISSUE TITLE
(again) Ever Vigilant activates pistol overwatch instead of rifle overwatch #496 

### ISSUE THREAD

**Issue by shyroy** [long-war-2/lwotc#772] opened 2019-11-27 14:19 UTC
I'm playing LongWarOfTheChosen-1.0-beta-2

Ever Vigilant activates pistol overwatch instead of rifle overwatch .
I've tested it for ranger class.

**Comment by pledbrook** [comment] 2019-11-27 14:24
Duplicate of #496 (but thanks for bringing it to my attention)

**Closed by pledbrook** 2019-11-27 14:24 UTC
Labels: duplicate
