### ISSUE TITLE
Too many corpses are rewarded

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#987] opened 2020-05-08 06:42 UTC
[save_AUTOSAVE- Campaign 77, Mission 105, Turn 5.zip](https://github.com/long-war-2/lwotc/files/4597361/save_AUTOSAVE-.Campaign.77.Mission.105.Turn.5.zip)
![20200508023455_1](https://user-images.githubusercontent.com/54481962/81378488-624f0100-90d5-11ea-8ad9-024ed114c2d7.jpg)

End the mission by killing the Sectoid (with the Shinobi)

Despite there only being one Muton Elite on the entire mission (the dominated one), I obtain three corpses at the end of the mission. All other enemy corpses are properly accounted for, so I assume that this was caused by 2 of the Sectoids summoning zombies.

**Comment by McTrevor79** [comment] 2020-05-08 07:10
I would say, you are experiencing this issue #928 . The issue is probably caused by dominating the Muton Elite rather than the psi zombies. Also works for archons and even controlled mecs.

**Comment by allenhu0912** [comment] 2020-05-08 16:06
This happened again in the next mission, where I dominated 2 Muton Elites and an Andromedon (total of 2 Muton Elites and 2 Andromedons on the mission)

![20200508120244_1](https://user-images.githubusercontent.com/54481962/81424651-46268080-9124-11ea-9f35-7aee3f3b58c8.jpg)

It seems to be caused by killing any enemy at all while a unit is dominated

**Comment by copyrite** [comment] 2023-12-19 18:10
More likely explanation is a mod like [[WOTC] Loot Mind Control](https://steamcommunity.com/sharedfiles/filedetails/?id=1130134672) or [[WOTC] Dude, Where's My Loot?](https://steamcommunity.com/sharedfiles/filedetails/?id=2878818143). Their compatibility with LWOTC have not been completely resolved yet. There's an issue about this on a fork and I'll get it moved to this repo soon.

**Comment by copyrite** [comment] 2023-12-21 20:11
Closing as duplicate of #1639, let's take that discussion there.

**Closed by copyrite** 2023-12-21 20:11 UTC
