### ISSUE TITLE
Smash and grab unreachable crate

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#326] opened 2019-07-11 21:26 UTC
An unreachable crate appeared on the 4th floor on the 'lost ruined city' map. Confirmed that I couldn't reach it with an advent hunter drone (hacked) or regular troops. As a result I lost the crate.

**Comment by BlackRose39** [comment] 2019-07-12 00:41
Can confirm that does indeed happen in my games.

**Comment by pledbrook** [comment] 2019-07-12 04:20
Duplicate of #315

**Closed by pledbrook** 2019-07-12 04:20 UTC
Labels: duplicate
