### ISSUE TITLE
Bomb Strapped Car Asset Missing Low Cover

### ISSUE THREAD

**Issue by Chaotic-Entropy** [long-war-2/lwotc#571] opened 2019-09-19 18:54 UTC
The low cover for the pictured map asset appears to be missing from both squares on the rear, bomb strapped car with left side door open. Using no other map related mods.

Part of data recovery mission.

![20190915104928_1](https://user-images.githubusercontent.com/55556991/65272488-15eb8c80-db17-11e9-905f-f896a299257c.jpg)

**Comment by Chaotic-Entropy** [comment] 2019-10-27 11:47
#707

**Comment by Chaotic-Entropy** [comment] 2019-10-27 11:47
Duplicate of #707

**Comment by Grobobobo** [comment] 2020-09-23 16:34
Duplicate of #707

**Closed by Grobobobo** 2020-09-23 16:34 UTC
