### ISSUE TITLE
Lost Appearing in ambush mission

### ISSUE THREAD

**Issue by Tylon01** [long-war-2/lwotc#68] opened 2019-04-08 21:55 UTC
I do not know what your plans are for the incorporation of the lost within lwotc 

however because I have not seen the lost appear on any maps prior to this event I was thinking that they were disabled for the time being. 

I had a Ambush event pop up with the sitrep of The Lost. On this map swarms of the lost were generated. 

[LostAppear.zip](https://github.com/pledbrook/lwotc/files/3056455/LostAppear.zip)

**Comment by ansabalirai** [comment] 2019-04-08 23:36
Yes, happened to me too, but I guess they are always supposed to appear on ambush missions. Free XP I guess?

**Comment by Tylon01** [comment] 2019-04-08 23:51
I may be in the minority, but I really enjoy The Lost.

**Comment by pledbrook** [comment] 2019-04-09 05:04
As I understand it, there are two situations in which the Lost can appear:

 * Via a randomly generated SitRep for a mission
 * The map itself forces the Lost to appear (for example, all abandoned city plots)

The random generation of SitReps is currently disabled for missions, partly because they are likely to exhibit bugs and balance issues that I don't want to deal with yet.

The mission in the attached save file is on an abandoned city plot, hence why the Lost are active. That's expected and I don't have any intention to disable that behaviour at this point.

The only issue I really have with The Lost is the lack of a cap on XP that can be gained from them on any one mission.

BTW, thanks for all the save files. Very helpful!

**Comment by Tylon01** [comment] 2019-04-09 11:21
Not a problem , I am glad to help. 

I will do some further testing regarding the lost generating on abandoned city plots.

**Comment by pledbrook** [comment] 2019-04-09 17:41
Closing this for now as this is expected behaviour. Either reopen or raise a separate issue if there is a problem.

**Closed by pledbrook** 2019-04-09 17:41 UTC
