### ISSUE TITLE
Crash on a mission start

### ISSUE THREAD

**Issue by Voker57** [long-war-2/lwotc#847] opened 2020-01-15 15:53 UTC
Save: [save.zip](https://github.com/long-war-2/lwotc/files/4065746/save.zip)
wait until mission infiltrates to 100%, then start it
Mods: required, recommended, CapNBubs accessories pack for WoTC https://steamcommunity.com/sharedfiles/filedetails/?id=1123427895
OS: Linux

**Comment by zygny** [comment] 2020-01-15 20:35
Possibly a duplicate of: #829 ?

**Comment by Grobobobo** [comment] 2022-01-17 16:44
Duplicate of  #829. Nothing we can do about linux either way.

**Closed by Grobobobo** 2022-01-17 16:44 UTC
