### ISSUE TITLE
Region still generate missions after failed intel mini-retaliation

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#400] opened 2019-08-10 15:08 UTC
![20190810225531_1](https://user-images.githubusercontent.com/53558693/62823429-37c22d00-bbc3-11e9-93a0-293726b3d39f.jpg)
As you can see,West Asia is intel prohibited,no one in on intel job.Still,there are missions pop up,and they have decent time to infiltrate.
In original LW2,when intel retaliation failed,intel collection ability is prohibited for 21 days.
So is this a bug?

**Comment by pledbrook** [comment] 2019-08-10 15:13
Do you have a save file shortly after the failed defence of the intel mini retaliation?

**Comment by jmartinez989** [comment] 2019-08-10 15:16
This is another case of spare rebel intel income that was generated before the intel retal. If you have enough rebel income in a region to spawn some missions before a retal and fail to protect the data tap then you can still generate a few. Especially if you scan in that area as that also generates intel income.

Unless of course you mean it still generates missions at the same rate. Then that is an issue but it is possible to generate a few missions after failing a failed intel retal in the region it happened in.

**Comment by ansabalirai** [comment] 2019-08-10 15:41
What @jmartinez989 said can be confirmed by looking in the log on whether the mission detection chances in a region are increasing after the failed intel retal. Not sure if the failed intel retal also limits intel gathering by avenger scanning, but you should not see the chances go up significantly when no rebels are assigned to intel.

**Comment by Sinkingeye** [comment] 2019-08-11 16:53
> 
> 
> This is another case of spare rebel intel income that was generated before the intel retal. If you have enough rebel income in a region to spawn some missions before a retal and fail to protect the data tap then you can still generate a few. Especially if you scan in that area as that also generates intel income.
> 
> Unless of course you mean it still generates missions at the same rate. Then that is an issue but it is possible to generate a few missions after failing a failed intel retal in the region it happened in.

I guess yoou are right,during playthrough there IS no mission generated in the following weeks.
Still,the fact that missions will spawn without intel is somewhat confusing.

**Comment by jmartinez989** [comment] 2019-08-12 07:08
> 
> 
> > This is another case of spare rebel intel income that was generated before the intel retal. If you have enough rebel income in a region to spawn some missions before a retal and fail to protect the data tap then you can still generate a few. Especially if you scan in that area as that also generates intel income.
> > Unless of course you mean it still generates missions at the same rate. Then that is an issue but it is possible to generate a few missions after failing a failed intel retal in the region it happened in.
> 
> I guess yoou are right,duringplaythrough there IS no mission generated in the following weeks.
> Still,the fact that missions will spawn without intel is somewhat confusing.

Again it's not that they are spawning without intel, it's that they are spawning from the intel that was left from the intel generated by the rebels before the retaliation.

**Comment by pledbrook** [comment] 2021-01-07 13:12
This is working as intended currently, even if it's a bit confusing.

**Closed by pledbrook** 2021-01-07 13:12 UTC
Labels: wontfix
