### ISSUE TITLE
Injured grenadiers will unequip flashbangs and turn them into sting grenades others can use or sell

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#442] opened 2019-08-27 02:03 UTC
![20190826194516_1](https://user-images.githubusercontent.com/54481962/63735301-58d67f00-c84d-11e9-9945-a151b7524a1b.jpg)

**Comment by pledbrook** [comment] 2019-08-27 06:11
Is this a duplicate of #360? Which version of LWOTC are you playing?

**Comment by allenhu0912** [comment] 2019-08-29 18:45
This was the Aug 20 version

**Closed** 2019-10-22 16:38 UTC
Labels: bug
