### ISSUE TITLE
SPARKs can infiltrate two missions at once again

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#1341] opened 2021-06-16 04:14 UTC
I think this is #609 resurfacing, but I can't be sure. Attaching save file where SPARK 001 is infiltrating one mission and still allowed to go on another. Prior to this the SPARK was damaged and I sent him out while it was being repaired, and it was able to heal while infiltrating as well.

[SparkBug.zip](https://github.com/long-war-2/lwotc/files/6660209/SparkBug.zip)
![20210615230825_1](https://user-images.githubusercontent.com/54481962/122156803-5765b480-ce2f-11eb-93df-e32f34292a64.jpg)
![20210615230839_1](https://user-images.githubusercontent.com/54481962/122156808-5a60a500-ce2f-11eb-8d2e-58105a79a677.jpg)

**Comment by pledbrook** [comment] 2021-06-22 09:05
I think it's a recurrence of an older issue. Praetorian should just be showing as "Infiltrating", not "Ready | Infiltrating". This is more likely related to #232.

The problem is that the SPARK's status is `eStatus_Active`, rather than `eStatus_CovertAction`. I don't know how it got into that state.

**Comment by pledbrook** [comment] 2021-06-22 09:08
Yeah, if I abort the infiltration and then start it up again with Praetorian, in the squad, the status is displayed correctly as just "Infiltrating".  So I really need the save just before Praetorian was sent on that mission.

**Comment by allenhu0912** [comment] 2021-06-22 14:19
This is what happened:

Praetorian is damaged on mission A. It is put in Engineering and partially repaired.

I sent it out on mission B. While infiltrating, it somehow continues repairing until hp is full.

After sending it out on mission B, regardless whether or not it is fully repaired, I can send it out on a second mission.

That is to say, I suspect this is caused by the SPARK being damaged. Because the SPARK buggily finished its repairs while infiltrating, you can't trigger the bug just by pulling it out of infiltration.

**Comment by DSeyka** [comment] 2021-06-24 08:39
>While infiltrating, it somehow continues repairing until hp is full.
I'm pretty sure this was the case in LW2 as well and just never got fixed.

**Comment by Tedster59** [comment] 2023-06-16 19:37
should be fixed in latest beta.

**Closed by Tedster59** 2023-06-16 19:37 UTC
