### ISSUE TITLE
problem with the detailed squad list portion

### ISSUE THREAD

**Issue by Sabonnel** [long-war-2/lwotc#381] opened 2019-08-01 15:28 UTC
not sure if ive done something wrong with the install or if this is an issue, but my squad list in the armoury is just showing the vanilla info, not the detailed stats under the names part, could someone help.
![20190801162532_1](https://user-images.githubusercontent.com/53571654/62306224-53b62800-b479-11e9-8d28-1af1e68c375e.jpg)

**Comment by jmartinez989** [comment] 2019-08-01 15:31
Do you have any other mods that override the detailed soldier list? lowtc has integrated the detailed soldier list mod that is on steam so if you have either that or any other mod that affects this list it could cause this. I am running the latest build and I do not have this problem.

**Comment by Sabonnel** [comment] 2019-08-01 15:34
all i have are the 2 folders in the LongWar2_WOTC-1.6-alpha-5.1.zip, and the 2 replacement files, LW_Overhaul.u and LW_Toolbox_Integrated.u.

nothing else

**Comment by jmartinez989** [comment] 2019-08-01 15:37
do you have any other mods installed at all? If not then try clearing your config folder in the "my documents" folder where xcom2 keeps its configs. That might fix it.

**Comment by Sabonnel** [comment] 2019-08-01 15:47
I, it would appear am a fool, and you good sir, are a diamond, i completely forgot to clear the config folder, worked like a charm, many thanks

**Comment by jmartinez989** [comment] 2019-08-01 16:00
no problem. closing as the issue is now fixed.

**Closed by jmartinez989** 2019-08-01 16:00 UTC
