### ISSUE TITLE
Ruler Aliens are AWOL.

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#797] opened 2019-12-07 16:21 UTC
Since completing "the Nest" Story mission.. I've never come across a Ruler Alien, fought around 50-70 Missions so far and never seen them once.

**Comment by wortkarg** [comment] 2019-12-07 16:30
Grobobobo's answer from Discord:
_They aren't working correctly for now
with nest mission they don't show up on all missions except avenger defence
without it they don't show up at all because lw facilities are different than vanilla facilities_

**Comment by maldun** [comment] 2019-12-17 17:17
This has to be newer than, there was a video pre-beta run by SG_Kaen on twitch where the rulers can be encountered [during other missions too](https://www.twitch.tv/videos/478519820?t=02h07m08s)

**Comment by spankahontis** [comment] 2019-12-17 21:10
> 
> 
> This has to be newer than, there was a video pre-beta run by SG_Kaen on twitch where the rulers can be encountered [during other missions too](https://www.twitch.tv/videos/478519820?t=02h07m08s)

Is there a link to the new Beta version? I probably have an old version.

**Comment by maldun** [comment] 2019-12-18 14:24
Have a look also on this issue: #279 I just found it recently, I think this explains how the current mechanic works. Seem to be a thing due to long war.
For an Overview of the releases just check them on the [releases page](https://github.com/long-war-2/lwotc/releases)

**Comment by spankahontis** [comment] 2020-01-03 20:34
Strange thing is maldun, I just managed to get the Ruler Alien, the Beserker Queen in one of my missions just now; after 150 Missions, one finally appeared, ddn`t manage to kill it.

I'm already fully kitted out in Warden Armour and Plasma weapons, 4 Liberated Regions and i'm facing late game aliens.

True to what Kazinir stated, the Mission I encountered the Ruler Alien in was in a Troop Column Mission.
I've fought about 10 so far in this campaign and this is the first time a Ruler appeared in one.

**Comment by Clibanarius** [comment] 2020-01-04 09:38
I kept trying to tell you all months ago that Rulers in LW2 almost exclusively appeared on troop column ambushes. It's where I've seen literally every instance of a Ruler's appearance in LW2 in many thousands of hours of play time. :P

**Comment by pledbrook** [comment] 2020-02-16 11:23
Duplicate of #279 (sort of)

**Closed by pledbrook** 2020-02-16 11:23 UTC
Labels: duplicate
