### ISSUE TITLE
Abandon Soldier Survives

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#390] opened 2019-08-05 01:09 UTC
Was on a Smash n Grab mission. The turn the EVAC arrived, a squadie went down and started bleeding out. No one was in range to grab him, so he got left behind. After mission report:  He leveled up, is gravely wounded, and is on the Avenger.

Presumably a bug with the "Captured Soldier" mechanic?

**Comment by pledbrook** [comment] 2019-08-08 08:52
I think this is a duplicate of #238

**Closed by pledbrook** 2019-08-08 08:52 UTC
Labels: duplicate
