### ISSUE TITLE
unable to retrieve data cache on mission

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#336] opened 2019-07-13 22:43 UTC
see save:
https://www.dropbox.com/s/eiiehij1ecq721t/save_Save%20158?dl=0

Soldier moves up to data cache and can't retrieve it to complete the mission (no option to interact with the cache). Not using any other mods except the kill count tracker.

**Comment by jmartinez989** [comment] 2019-07-14 00:05
did a save and reload fix it? this happens to me a lot and I have to save reload to fix it. This is definitely something that needs to be looked into but will probably take a back seat to some other stuff that is higher priority for now. Thank you for the save though.

**Comment by captainbeastfeast** [comment] 2019-07-14 00:49
I tried loading my save and the issue remains. will probably have to use console commands to finish this 1. First time this has happened to me as of yet..

**Comment by BlackRose39** [comment] 2019-07-14 19:54
I found the issue, the soldier at the cache had NEGATIVE hack statistics. See screenshots.

![20190714135001_1](https://user-images.githubusercontent.com/44072125/61188592-b1a3dc80-a63e-11e9-8d5d-ee24ee4990a9.jpg)
![20190714134959_1](https://user-images.githubusercontent.com/44072125/61188596-b8325400-a63e-11e9-83ab-88cc99c4650b.jpg)
![20190714135017_1](https://user-images.githubusercontent.com/44072125/61188597-bbc5db00-a63e-11e9-864f-c6bc05c1c1f2.jpg)
![20190714135023_1](https://user-images.githubusercontent.com/44072125/61188599-c2ece900-a63e-11e9-9abc-ca8d6319292a.jpg)

When I teleported Felix, who had at least one hack status, he was able to hack it.

The problem is that when a soldier's hack status goes below 0 (perhaps from penalties from red fog for example), they will be unable to perform a hack. In fact, this has been an issue referenced from other sources since the original long war 2.

https://www.reddit.com/r/Xcom/comments/6ju0os/is_there_a_reason_i_cant_hack_this_thing/

There should be some indications that the soldier can't perform the hack because of no hack stat, or still be able to hack with 0 or negative hack stats, but maybe with 0% chance of getting rewards. This was how it was back in the original long war 2, but I still think it's a bug overlooked by the original team that has caused many scratching heads and should be addressed.

A temporily fix would

**Comment by BlackRose39** [comment] 2019-07-18 02:26
Just came back after thinking about it, but it might be tactically done on purpose where you have to bring another squad member/medikit to cover up the injured/debuffed soldier in case they can't hack. 

I'm torn on this, any thoughts whether a bug or not?

**Comment by wdanny69** [comment] 2024-04-11 22:13
fixed in #1701 , hack no longer penalized with red fog

**Closed by wdanny69** 2024-04-11 22:13 UTC
Labels: bug, has:save
