### ISSUE TITLE
Many Psi ablities do not damage organic targets. 

### ISSUE THREAD

**Issue by JackieNCB** [long-war-2/lwotc#979] opened 2020-05-05 18:32 UTC
Abilities like Soulfire and Void Rift do no damage. While Null Lance and Schism does. 

Any reason why?

**Comment by Grobobobo** [comment] 2020-05-05 18:45
No psi changes has been made just yet, so no idea.

**Comment by copyrite** [comment] 2023-12-19 18:29
There have been no such reports for a long time, closing. Post a new one if the issue is still relevant and persists.

**Closed by copyrite** 2023-12-19 18:29 UTC
