### ISSUE TITLE
Spark Nova can sometimes graze

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1673] opened 2024-02-09 00:08 UTC
Issue: The Nova ability that Sparks can obtain can sometimes graze the target only dealing half damage.

Expected Behavior: Nova is meant to be a guaranteed damage ability so it should not have the possibility to roll graze.

Potential issue: it seems like there is no guaranteed damage being set which may be why it is not completely guaranteed
![image](https://github.com/long-war-2/lwotc/assets/39199279/34885145-ae47-4a00-8f4e-846856f4976e)

**Comment by Tedster59** [comment] 2024-02-09 00:47
Nova uses default.deadeye which is already a guaranteed hit.  LW graze band will not touch abilities that use default.deadeye, or you'd get stuff like medikits, combat protocol, etc grazing.  Can't reproduce with my own test right now:

![image](https://github.com/long-war-2/lwotc/assets/21696818/0157cd28-7179-4155-b1fd-bb5767a95752)

**Comment by Tedster59** [comment] 2024-02-09 02:09
Turns out the cause is explosive falloff applying, so fixed with exclusion in https://github.com/long-war-2/lwotc/commit/1f16588fce13ebb40d1b3582eb300746a0fc77cc

**Closed by Tedster59** 2024-02-09 02:09 UTC
