### ISSUE TITLE
Squad Management sorting column headers broken; labeled LABEL all.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#495] opened 2019-09-08 15:58 UTC
![whaaaaaaaaaaaaaaaaaaaaaaaaaaat](https://user-images.githubusercontent.com/54611482/64490903-7df0c780-d227-11e9-9f67-eeed612fcc62.jpg)

**Comment by Clibanarius** [comment] 2019-09-08 15:58
They don't sort, either. Actually clicking the header of the column in question does not change the ascending/descending sort state.

**Comment by BlackRose39** [comment] 2019-09-11 05:54
#320

**Comment by pledbrook** [comment] 2019-09-15 09:25
Duplicate of #320

**Closed by pledbrook** 2019-09-15 09:25 UTC
