### ISSUE TITLE
Haven adviser not returning from haven assault mission

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#222] opened 2019-06-10 11:26 UTC
The adviser assigned to the mission is lost after evacting all units.
I'm not sure yet what happened to the guy but this was the second time this happened.

Save file at:
https://drive.google.com/file/d/1hSU1iEHttLvSharthb0nKvy0RfhC9kdI/view?usp=sharing

I think the soldiers lost like this might be counting as captured since bonds still list the missing soldier but I'm unable to very this now.

**Comment by pledbrook** [comment] 2019-06-10 11:31
Is this alpha 4? If so, has that haven adviser ever been on another retaliation mission?

**Comment by torma** [comment] 2019-06-10 21:17
When I came back to github to raise the issue I have noticed that alpha 4 is out. So I reloaded with alpha 4 and the same thing happened.

**Comment by pledbrook** [comment] 2019-06-11 05:01
If that haven adviser is already corrupted, then alpha 4 won't fix that. It just prevents any more haven advisers becoming corrupted in the same way. I'm going to assume this is that same issue unless you have evidence to the contrary.

**Comment by torma** [comment] 2019-06-11 20:45
Well that would explain that.
If I come across the same issue again in aplha4 I'll create a new issue.
Thanks for explaining.

**Comment by jmartinez989** [comment] 2019-06-23 15:24
opening this back up as the issue seems to be only occuring on the Haven Defense retaliation (The one where the mission starts with no enemies but has rnfs every turn). Looking into this.

**Comment by pledbrook** [comment] 2019-06-23 19:47
The issue is that the `SquadTacticalToStrategyTransfer()` function clears the `bRemovedFromPlay` flag on all units, including the haven adviser, before the `LWOutpost.UpdatePostMission()` is called. And that checks the `bRemovedFromPlay` flag to determine whether the haven adviser got out of the mission OK.

**Closed** 2019-06-24 09:31 UTC
