### ISSUE TITLE
Instant crash on startup.

### ISSUE THREAD

**Issue by Kerbomancer** [long-war-2/lwotc#193] opened 2019-06-01 16:22 UTC
I launch the game via the launcher and it instantly crashes. I don't get to see logos or anything. No other mods are installed. 
I already tried deleting the configs, disabling and enabling, and updating drivers. I think some configs may be missing? Here's the log.

https://pastebin.com/iY0azSBn

**Comment by pledbrook** [comment] 2019-06-01 19:10
Make sure you have an up-to-date version of the game. Try the "Verify Integrity of Game Files..." option in Steam. You definitely have WOTC, right? Just want to make sure.

**Comment by Kerbomancer** [comment] 2019-06-01 20:27
Yes. The game is up to date. I'll reinstall it, just in case. I already tried verifying game files and there was no  problem.

**Comment by pledbrook** [comment] 2019-06-01 20:55
Could you also try with just the community highlander from the workshop? It doesn't look like a LWOTC-specific error.

**Comment by Kerbomancer** [comment] 2019-06-01 22:47
https://pastebin.com/Ly5Wwg64

Still getting the same error. It seems to look for something in the game directory, or find something it doesn't want to find.

**Comment by robojumper** [comment] 2019-06-01 23:03
Your game is evidently not up to date. Current versions of the game print

    Init: Compiled (64-bit): Sep 13 2018 03:53:23
    Init: FxsChangelist: 374751

while yours prints

    Init: Compiled (64-bit): Aug 18 2017 22:12:28
    Init: FxsChangelist: 302202

**Comment by Kerbomancer** [comment] 2019-06-01 23:04
Hm. I'll update it, thanks.

**Comment by Kerbomancer** [comment] 2019-06-03 22:39
Now I've updated it (Init: FxsChangelist shows what it should) but I still get crashes, after the logos play the music starts, stutters, and the game crashes.
I nuked the MyDocuments/Xcom2WarOfTheChosen folder. Still have the backup just in case. The game generated a new one anyway.
https://pastebin.com/jAbJU68m

**Comment by pledbrook** [comment] 2019-06-04 08:46
You have another highlander running, not the one that comes with LW2. Are you subscribed to the community highlander?

**Comment by Kerbomancer** [comment] 2019-06-04 14:23
I followed the instructions here.
https://github.com/long-war-2/lwotc/wiki/Play-testing-Long-War-2-%5BWOTC%5D
I downloaded it again, deleted all in mods, pasted, and it still crashes.

**Comment by pledbrook** [comment] 2019-06-04 14:32
Your last log showed this error, which is definitely the cause of the crash:
```
[File:G:\BuildAgent\work\9a884cb2af69f6ff\main\XCOM2\Development\Src\Core\Src\UnObj.cpp] [Line: 2456]
Failed to find function SubscribeToOnInput in UIScreenStack 
```
`SubscribeToOnInput()` is provided by the community highlander.

Do you have "X2WOTCCommunityHighlander" selected in the mod list when you start the game? Definitely? If so, what other mods do you have enabled?

**Comment by Kerbomancer** [comment] 2019-06-04 15:06
Yes. I only have LWotC2 enabled.

**Comment by Kerbomancer** [comment] 2019-06-04 15:38
I tried redownloading everything, but still no luck. I deleted both mods beofre pasting them back in.

**Comment by Kerbomancer** [comment] 2019-06-04 16:17
I saw a dev version of the highlander. Should I use that one?

**Comment by pledbrook** [comment] 2019-06-04 16:19
> Yes. I only have LWotC2 enabled.

You need to have "X2WOTCCommunityHighlander" enabled too.

**Comment by Kerbomancer** [comment] 2019-06-04 16:19
I have it on. I tried launching with Highlander only and it still crashes.

**Comment by pledbrook** [comment] 2019-06-04 16:20
Can you post the log file for when you just have the highlander enabled?

**Comment by Kerbomancer** [comment] 2019-06-04 16:23
https://pastebin.com/SmM2Btmc

**Comment by pledbrook** [comment] 2019-06-04 16:33
From that log file:
```
[0025.54] X2WOTCCommunityHighlander: Companion script package loaded
[0025.54] X2WOTCCommunityHighlander: Components:
[0025.54] X2WOTCCommunityHighlander:   X2WOTCCommunityHighlander -- v1.18.2
[0025.54] X2WOTCCommunityHighlander:   Engine -- NOT LOADED - REQUIRED
[0025.54] X2WOTCCommunityHighlander:   XComGame -- NOT LOADED - REQUIRED
[0025.54] X2WOTCCommunityHighlander: Required packages were not loaded. Please consult https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting for further information
```

**Comment by Kerbomancer** [comment] 2019-06-04 16:35
So...restore the MyDocuments/XCOM2WoTC backup?

**Comment by pledbrook** [comment] 2019-06-04 16:39
As the log message states, you'll need to follow the troubleshooting steps [here](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting).

This is not an issue with LW2 [WOTC], so closing.

**Closed by pledbrook** 2019-06-04 16:39 UTC
