### ISSUE TITLE
Advent supply Crate spawns off the top of the map

### ISSUE THREAD

**Issue by Tethrinaa** [long-war-2/lwotc#1321] opened 2021-06-03 04:55 UTC
I used the console to teleport my guy around to try to find it, no luck.  Icon definitely looks like it is off the top of the map.

These city maps are annoying for tagging crates anyways, because they are so hard to even find on the multiple levels/balconies.

![Rooftop Supplies](https://user-images.githubusercontent.com/14298379/120589027-38662c00-c406-11eb-9fd0-43cae289f14c.png)

**Comment by Tethrinaa** [comment] 2021-06-03 04:56
![image](https://user-images.githubusercontent.com/14298379/120589258-9266f180-c406-11eb-8b30-1400eab14e1c.png)

**Comment by TwinuX** [comment] 2021-06-03 04:58
This is a known WOTC bug. Firaxis incorrectly configured some of the crate spawns, so they spawn on top of the apartments.
Not an easy fix.

**Comment by pledbrook** [comment] 2021-06-12 12:38
Duplicate of #568

**Closed by pledbrook** 2021-06-12 12:38 UTC
