### ISSUE TITLE
Pistol Perk issue

### ISSUE THREAD

**Issue by noirforest** [long-war-2/lwotc#601] opened 2019-09-24 15:17 UTC
Sorry I dont upload a save or any screenshoot, due to I dont play LWTOC on English.

1,Losing all pistol Perk in the battle if you dont equip at least 1 item with your pistol
When you equip pistol in your first unitly slot and the other 2 slots is empty, you wont have any unlock pistol perks during the mission. But if you equip at least 1 item with pistol in the untily slots, everything is fine.

[https://cdn.discordapp.com/attachments/590853932314656778/626075089552670720/test1.jpg](url)
[https://cdn.discordapp.com/attachments/590853932314656778/626075127121051648/test2.jpg](url)
2,Out of ammo on every unlock pistol shooting perks
Standard Pistol Shoot and Pistol Overwatch work, but the other perks:Clutch Shot,Lightning Hands,Fan Fire and Gunslinger state out of ammo. Faceoff has a little difference, the soldier could shoot, but with their primary weapon animation and deal no damage.

**Comment by pledbrook** [comment] 2019-11-01 08:22
Duplicate of #488

**Closed by pledbrook** 2019-11-01 08:22 UTC
Labels: duplicate
