### ISSUE TITLE
CTD at mission completion for certain mission types.

### ISSUE THREAD

**Issue by Drask007** [long-war-2/lwotc#485] opened 2019-09-05 15:21 UTC
I'm getting CTD's upon completion for the following mission types:
Ambush Enemy Troop Column (On last kill)
Destroy the Monument (On planting the X4 after all enemies have been neutralized)
Kill the Resistance spy (On last kill)

Evac missions are all working fine, It seems to just happen on the final kill or activate missions. Reloading a save for the final turn seems to fix it though.

I only have the required mods loaded for LWOTC, None of the supplemental mods. Uploading a save seems kind of pointless, since a reload seems to fix it. So, if I know that this is about to happen, i can save the game, reload, and it won't crash. This is the only mod that I've had crashing issues with XCOM 2.

**Comment by pledbrook** [comment] 2019-09-05 15:31
Do you have any other mods installed but disabled? Have you tried the usual sanitation procedure of clearing out your personal config directory and moving _profile.bin_ out of the _SaveData_ directory?

**Comment by Drask007** [comment] 2019-09-05 16:52
I'm giving that a shot now. Do I have to unsubscribe to the mods? I have them all disabled but the suggested ones. I have over 300 mods subscribed. Disabling them with the alternate launcher always seemed to work fine though.

**Comment by pledbrook** [comment] 2019-09-05 16:54
If the problem is a mod conflict, then it's best to unsubscribe to fully be sure. Just disabling mods doesn't seem to guarantee that they won't be at least partially loaded.

**Comment by Drask007** [comment] 2019-09-05 19:52
My mods folder only has the ones that I have enabled in it. Just had the crash happen again on a supply raid (kill all enemies on the train).

**Comment by Drask007** [comment] 2019-09-06 16:39
Unsubscribing and doing the sanitation procedure again didn't help. I'm not getting any redscreens on my loads. Also, verified my game files.

Would it be pointless to re-download and reinstall the mod? Like I mentioned earlier, I never had this issue with other mods. Just LWOTC. Some of my regional bonuses don't seem to be working either. Specifically the ammo and bomb proving grounds ones. Those projects are supposed to complete instantly, but that doesn't happen.

**Comment by BlackRose39** [comment] 2019-09-15 23:24
Hello Drask007. Could you upload/paste your log files here? (The one with the crash) It may help the coders to pinpoint where the issue is.

**Comment by Drask007** [comment] 2019-09-15 23:48
I'm currently out of town, but I'll send them when I get the chance.

**Comment by Drask007** [comment] 2019-09-19 07:40
[XCom-CL374751-2019.09.19-01.30.35_Logfile.log](https://github.com/long-war-2/lwotc/files/3629998/XCom-CL374751-2019.09.19-01.30.35_Logfile.log)

[XCom-CL374751-2019.09.19-01.30.35_Logfile.log](https://github.com/long-war-2/lwotc/files/3629999/XCom-CL374751-2019.09.19-01.30.35_Logfile.log)

**Comment by copyrite** [comment] 2023-12-20 19:19
Closing as old and one end-of-mission crash having been fixed.

**Closed by copyrite** 2023-12-20 19:19 UTC
