### ISSUE TITLE
Covert Ops: Got reward on a failed mission

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#1094] opened 2020-08-04 07:17 UTC
Doing an op for the Templars to recruit an Engineer. The op failed, but I received the staff anyways.

Save is from the day before the mission completes.
[save_AUTOSAVE- Campaign 12, Mission 43.zip](https://github.com/long-war-2/lwotc/files/5020685/save_AUTOSAVE-.Campaign.12.Mission.43.zip)

**Comment by Grobobobo** [comment] 2020-09-23 10:12
Duplicate of #1018

**Closed by Grobobobo** 2020-09-23 10:12 UTC
