### ISSUE TITLE
Naja (Sniper snake) can move and attack (and should not be able to)

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#162] opened 2019-05-11 12:11 UTC
Najas, also known as sniper snakes, should not be able to move and attack. They use a sniper rifle that should require 2 actions to fire. It seems that they ignore that restriction at the moment.
Example:  https://www.twitch.tv/videos/423358303?t=03h25m55s

Autosave from previous turn attached:

[snapshot_naja.zip](https://github.com/long-war-2/lwotc/files/3169003/snapshot_naja.zip)

**Comment by jmartinez989** [comment] 2019-05-11 16:57
yeah they definitely can. This might mean that their rifles just don't cost 2 actions to use. I need to look at the ini files and look at their loadouts to see what their weapons  have in terms of ap per shot.

**Comment by jmartinez989** [comment] 2019-05-11 17:28
Im pretty sure that I have confirmed that the naja sniper rifles only cost 1 ability point to shoot as I do not see the line Template.iTypicalActionCost = 2; in the weapon template that I see for other sniper rifles so I am going to add that and test.

**Comment by jmartinez989** [comment] 2019-05-12 02:59
Ok so this is indeed fixed. Will be pushing this up as soon as I get another pull request done (because of the way the work was done on the branches I have to wait until another branch is merged to master first.

**Comment by jmartinez989** [comment] 2019-05-18 15:47
This has been tested and committed as working. Closing.

**Closed by jmartinez989** 2019-05-18 15:47 UTC
Labels: bug, has:save, has:solution
