### ISSUE TITLE
Soldier turns into Flying Spaghetti Monster

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#751] opened 2019-11-22 13:48 UTC
As Crazy as the title suggests.. My Soldier who is a Psi Agent, took a shot, then it reacted like it was being shot at, even heard gunfire noise, but no ADVENT was shooting at her; you also see a message box appear above her briefly saying 'PROTECTED'
Then her entire Body  jumbles up into a cloud of limbs like a Flying Spaghetti Monster.

Funny to watch, Soldier goes back to normal after the mission.

Mods I have on
- Zhang Voicepack
- Japanese Voicepack
- More Nations and Names WOTC
-  Xcom International Voicepack
- Evac All WOTC
- Capnbubs Accessories WOTC
- Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)

[Soldier become Spaghetti Monster.zip](https://github.com/long-war-2/lwotc/files/3879764/Soldier.become.Spaghetti.Monster.zip)

**Comment by Anxoczt** [comment] 2019-11-22 21:14
Happened to me too... but in non WOTC and i was playing with RPGO, seems to be triggered by psiops scoring a killing blow. But it hasnt happened to me in LWOTC...yet.
![20180930200005_1](https://user-images.githubusercontent.com/50877085/69460863-6c728280-0d75-11ea-963f-db7c9d5b1ee1.jpg)

**Comment by spankahontis** [comment] 2019-11-23 21:21
Seems to only happen with my Psi Op Roya Modrassi.
It's happened 3 times with her since then.

Yeah, maybe Psi Op connection?

**Comment by DrBots276** [comment] 2019-12-02 02:16
I'm also having this problem, and I it's only soldier that have "the Gift". Do you guys have mods that affect Psi Ops?

**Comment by spankahontis** [comment] 2019-12-06 17:15
@DrBots, Every Mod I'm using non-essential is listed above.

All I know is she scores a kill, then she reacts like she is being shot at, that's when she jumbles into a spaghetti monster.
Maybe the Capnbubs Accessories? Nothing I have alters animations except Extract Corpses, but that just allows dead aliens to be picked up.

**Comment by DrBots276** [comment] 2019-12-06 19:02
Well the same thing happens to me, and I use both of those mods.

**Comment by aikomiko** [comment] 2019-12-11 04:36
Playing modded WOTC (but not including LWOTC mod at the time) I had this tactical mode 'soldier spaghettification' happen also.   

I've since completely changed game setup to test the new LWTOC beta, and reviewing my current modlist against yours, I am using "Evac All - WotC" but not "Capnbubs Accessories".  

So I have noted this same effect very rarely happening (only a few times total) on tactical gameplay (WOTC with 150+ mods at the time) so it seems LWOTC is not the root cause of this issue... this is the first time I've seen it on game launch.   

Now trying LWOTC beta 2 and a modlist that I slowly grew from the minimum to "minimum +recommended" and then up to current modlist.  

Now in the last few game starts I have had 'soldier spaghettification' on the launch page.  It seems to be a rare event so far.

It would be great to figure out what is getting the XCOM personnel all twisted up.   Modlist below.

<img width="1347" alt="Capture" src="https://user-images.githubusercontent.com/58750335/70591265-5ee93500-1b8a-11ea-90fc-ac87b972aded.PNG">

MODLIST
	WOTC Show Enemies and Terrain on Mission Planning                                         
	Instant Avenger Menus - WotC                                                                              
	[WotC] Instant Loot                                                                                         	
	WotC: robojumper's Squad Select                                                                          
	[WotC] Gotcha Again                                                                                         	
	Evac All - WotC                                                                                             	
	[WOTC] Additional Icons                                                                                 
	Better Second Wave Mod Support                                                                 
	[WOTC] Less Overwatch Lock Ups!                                                                 
	[WOTC] New Target Icons                                                                               
	WOTC Female Hair Pack                                                                                  
	[WOTC] Armored Viper                                                                                   
	[WotC] XCom 2 Community Pose Pack                                                                           	
	WOTC Male Hair Pack                                                                                         	
	WOTC New Heads Pack                                                                                         	
	[WotC] Mod Config Menu
        Commanders Choice [WOTC & Vanilla]                                                                          	
        Yet Another F1                                                                                              	
	Scientist Staff Slots: WotC Edition                                                                         	
        [WOTC] EU Berserker                                                                                         	
	Narrative Control                                                                                           	
	[WOTC] XCom Scamper                                                                                  
	[WOTC] Mechatronic Warfare: Total SPARK Overhaul                                     
	Show More Buff Details                                                                                   
	[WotC] Revival Protocol Fixes                                                                          
	[WOTC] Revert Overwatch Rules Change                                                        
	Improved Camera Updated WotC                                                                           
	[WOTC] Dedicated Pistol Slot
	[WOTC] Stats on New Promotion Screen                                                                
	[WotC][LWotC] Global Weapon Stat Changer                                                         
	[WotC+Classic] TacticalUI KillCounter                                                                     
	No Drop-down Lists                                                                                          	
	Long War of the Chosen                                                                                
	[BETA] X2WOTCCommunityHighlander                                                         
	[WOTC] Free Reload Anytime                                                                        
	[WOTC] Titanfall Sparks                                                                                 
	Bondmates With More Benefits                                                               
	FacesOfXcom                                                                                           
	Smart Overwatch All [WotC]                                                                            
	[WOTC] Peek From Concealment                                                                     
	WOTC Save Games Delete All Option                                                              
	Upcoming Events [WotC]                                                                                 
	[WotC] Peek From Concealment UI Fix                                                            
	No Reveal Cinematics                                                                                      
	Wotc dropship narrative blackscreen fix                                                         
	A Better Start for WOTC (LITE)                                                                              	
	A Better Arsenal for WOTC (LITE)                                                                            
	[WOTC] Reliable Wounds                                                                                      	
	[WotC] Strip Weapon Upgrades and Customization                                              
	[WotC] RW Realistic Aiming Angles                                                                        
	WC_PhotoReBooth

**Comment by DrBots276** [comment] 2019-12-11 04:42
Apparently this is a base game bug.

**Comment by Boomjones** [comment] 2020-04-20 21:01
I've been playing beta 2 and had the same bug, though in my case it only happens when a psi op with soul steal uses soulfire, and only about half the time. I'm certain of this as only 1 of my psi ops has soul steal, and that it the only one that's had the issue. 

Reloading a save seems to fix it.

**Comment by fedupwithbioware** [comment] 2020-05-19 12:43
Had this as well. Will have to upload my mods list and a save game later though.

**Comment by belathus** [comment] 2020-05-22 00:39
I have this happen regularly when a Psi Ops with Soul Steal gains life. Perhaps when scoring a kill with Soul Steal.

**Comment by Grobobobo** [comment] 2020-07-03 18:27
Fixed in dev 16.

**Closed by Grobobobo** 2020-07-03 18:27 UTC
