### ISSUE TITLE
Not sure if this is a bug but..

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#284] opened 2019-06-26 16:17 UTC
Sometimes I am able to field up to 10 soldiers in chosen base assault missions. Is this intended?

**Comment by Kazanir** [comment] 2019-06-26 16:29
Facility, HQ, Base, Golden Path, and Invasion (?) are all supposed to allow 10, yes. The penalties for infiltrating with the 9th or 10th guy are severe and that's intended behavior from LW2.

**Comment by jmartinez989** [comment] 2019-06-26 16:32
Yeah this is not a bug and is intended behavior. Closing this.

**Closed by jmartinez989** 2019-06-26 16:32 UTC
