### ISSUE TITLE
Dark Event: Gone to Ground bug

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#392] opened 2019-08-05 21:41 UTC
I was just hit with the dark event "gone to ground".  It states that the black market will be closed for 6 weeks.  I was immediately able to scan for a new black market (took 1 day).  Now the black market is open again but in a new location.  The dark event shows it is still active.

What will happen in 6 weeks?  Nothing, 2 black markets, or game explodes.  

I will have to play it out and give you an update later.

**Comment by pledbrook** [comment] 2019-08-08 08:44
Probably easiest to disable this dark event, particularly as the Black Market is so much more important in LW2 than the vanilla game.

**Comment by pledbrook** [comment] 2019-08-08 08:45
Duplicate of #258

**Closed by pledbrook** 2019-08-08 08:45 UTC
Labels: bug, duplicate
