### ISSUE TITLE
SitReps & DarkEvents cycle & Data gathering

### ISSUE THREAD

**Issue by zyxpsilon** [long-war-2/lwotc#983] opened 2020-05-07 15:48 UTC
https://discord.com/channels/590853492084572170/590905659076378625

Reference(s) linked here to continue discussing the "Issue" of strange incompatibility with my **_WC_PhotoReBooth_** mod & how we both (or maybe just me) should synchronize and validate our variations when/if necessary.

As explained in details overthere.. i am calling this stuff the wacky '' _PrivateChannelsSitRep_ '' fallback flaw anyway! :)

**Comment by pledbrook** [comment] 2020-05-08 06:19
I'm confused. "PrivateChannelsSitRep" is added by WOTC and has nothing to do with LWOTC. In fact, LWOTC disables it.

**Comment by pledbrook** [comment] 2020-05-08 06:23
I'm doubly confused as I'm not sure what the issue is with dark events. Note that the Dark Event sit reps are registered as normal sit reps. The only "magic" around them is how the dark events add the sit reps to missions (it's very simple), but that seems irrelevant to this use case because you're only interested in the active sit reps on the battle data, which will include the dark event sit reps.

**Comment by zyxpsilon** [comment] 2020-05-08 14:47
Oh.. but **that** info solves the detection problem itself since the possible active SitReps will always (whatever their origin may be) be contained into _BattleData_  while i scan for them within my PRB function(s) at Post-Mission times.

Still have to determine why "_PrivateChannelsSitRep_" string-tag gets pulled and then, shown as an indirect fallback state though.

Thanks anyway.

**Comment by pledbrook** [comment] 2020-05-08 14:52
The behaviour you're seeing would be explained by the Private Channels sit rep being assigned to a mission, but then later disabled (not registered as a sit rep). For example, if you upgrade from an old version of LWOTC that allows Private Channels, then a mission may spawn with it. Then when you upgrade to the latest LWOTC, Private Channels is disabled. Hence it doesn't appear as a registered sit rep.

That said, I don't remember ever releasing a version of LWOTC that had Private Channels enabled.

**Comment by zyxpsilon** [comment] 2020-05-08 15:43
Oh.. that should (yet -- could!) allow me to create an extra special condition _just_ for that weird code toggling flaw. Wicked Vanilla will never stop wrecking our stuff, i guess. ;)

**Comment by zyxpsilon** [comment] 2020-05-11 05:14
Problem solved.. all i needed was to insert this..
```
; LWoTC
+Icons = (IconName = PrivateChannels			, IconPath =	"PRB_UILibrary.iSRBL")
```
.. into the INI file to trick that false/disabled SitRep away towards the Fallback Icon.

You can now close that Issue!

**Comment by pledbrook** [comment] 2020-10-27 17:51
Closing as requested

**Closed by pledbrook** 2020-10-27 17:51 UTC
