### ISSUE TITLE
Game stuck completely after selecting grenadier

### ISSUE THREAD

**Issue by PodliKirill** [long-war-2/lwotc#379] opened 2019-07-31 13:03 UTC
Have bug with stucking game.

Logs:
[0112.60] Warning: USkeletalMeshComponent::SetRBRotation(): no PhysicsAssetInstance for SkeletalMeshComponent Plot_ABN_SupplyExtract_Waterfront.TheWorld:PersistentLevel.XComWeapon_52.SkeletalMeshComponent_460 with skeletalmesh: NULL                                                                                            [0114.93] Log: Tactical Load Debug: Post loading movie check                                                                                                      [0114.93] Log: X2TacticalGameRuleset_0 LoadTacticalGame: End of Begin Block                                                                                       [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_End: BeginState                                                                                                  [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_End: Start of Begin Block                                                                                        [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_End: End of Begin Block                                                                                          [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_Begin: BeginState                                                                                                [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_Begin: Start of Begin Block                                                                                      [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_Begin: End of Begin Block                                                                                        [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: BeginState                                                                                          [0114.93] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Start of Begin Block                                                                                [0114.95] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Check for Available Actions                                                                         [0114.95] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Going to the Next Player                                                                            [0114.96] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Waiting for Visualizer: 1                                                                           [0114.99] ScriptLog: XComTacticalInput.uc, Transition to/from State None detected. BeginState ActiveUnit_Moving from None                                         [0114.99] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Check for Available Actions                                                                         [0114.99] Log: X2TacticalGameRuleset_0 TurnPhase_UnitActions: Available Actions              

                              
Save - https://www.dropbox.com/s/sd5t0new4bd129o/save_Stucking%20grenadier?dl=0

**Comment by pledbrook** [comment] 2019-08-19 10:34
Sorry, I'm struggling to track down the cause of this bug. It may take a while, if I can do it at all.

**Comment by Favid** [comment] 2019-08-31 13:56
No idea what part of the code is causing this, but it's something to do with the Lost next to the Grenadier. If you kill that lost with another soldier, then you can select the Grenadier without issue.

**Comment by pledbrook** [comment] 2021-12-20 14:07
This is such a niche bug I'm going to close it. I doubt anyone will be able to get round to looking into it I'm afraid.

**Closed by pledbrook** 2021-12-20 14:07 UTC
Labels: bug, has:save
