### ISSUE TITLE
Bug on succeeding the HQ assualt

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#124] opened 2019-04-22 03:23 UTC
Different from the crash while loading into the HQ assault, I am having a blocking bug after succeeding the HQ and returning to strat layer. The avatar progress comes up and then the game hangs on the strat layer. Two save files are attached, one when the HQ has just reached 200% infiltration and another while loaded into tactical and all enemies are ded.
[HQ_crashes.zip](https://github.com/long-war-2/lwotc/files/3102041/HQ_crashes.zip)

**Comment by pledbrook** [comment] 2019-04-23 06:46
Interestingly, the tactical save didn't crash on me at any point after completing the mission. There may be a difference between Mac and PC or the mods installed. I'll have to test on PC.

Also, Flawless HQ?! Clearly they need to be made harder :wink:

**Comment by ansabalirai** [comment] 2019-04-23 16:46
That's interesting. So, I guess loading from strategy layer still causes the crash? 
I guess one of the 14 mods I am using could be a culprit. Someone was talking about commander's choice not playing nice, so maybe I can try disabling that.

Also, only flawless coz killallais. I did not want to do the HQ for the 100th time just to encounter the bug again

**Comment by pledbrook** [comment] 2019-04-23 20:45
I loaded your pre-mission save file as well, ran `killallais` in the mission itself, and came out of it fine. Avatar appeared, other missions popped up, etc. No crash.

**Comment by ansabalirai** [comment] 2019-04-23 21:00
I see. Most likely a mod conflict on my part I guess. I will thin out the mods (my fault entirely for letting it get away from me) and try again to see if it persists.

**Comment by pledbrook** [comment] 2019-05-17 18:19
Can't reproduce on PC with latest code either. Closing as not reproducible.

**Closed by pledbrook** 2019-05-17 18:19 UTC
Labels: blocker, bug, has:save

**Comment by ansabalirai** [comment] 2019-05-17 18:35
From a different discussion, I have heard people say that "instant avenger menus" is the culprit. Not sure though
