### ISSUE TITLE
Cannot place X4 during Chosen Avenger defense mission

### ISSUE THREAD

**Issue by eurofjr** [long-war-2/lwotc#1438] opened 2021-09-19 21:28 UTC
I'm playing the 1.0 beta 4.1 version using only the mods provided with Nexus download. I downloaded on 26 JUL so have the latest patch from 8 JUN. 

I'm doing a Chosen Avenger defense mission and cannot place the X4 on last of the smaller guns.  I've already destroyed the main gun and three of the smaller guns. But, no matter what I do, I cannot place the X4 and I've tried everything game-wise that I can think of, including restarting the mission. My next step will be to restart an earlier Geoscape save and see if the bug continues. If it does, and I'm stuck with this bug that won't allow me to complete the Avenger defense mission, I might have to restart the campaign. 

Attached is the save file.

**Comment by pledbrook** [comment] 2021-12-19 16:27
Duplicate of #1497

**Closed by pledbrook** 2021-12-19 16:27 UTC
