### ISSUE TITLE
Hacking a drone resulted in mind controlling another enemy

### ISSUE THREAD

**Issue by Q-Chaos** [long-war-2/lwotc#1577] opened 2022-12-04 19:24 UTC
So, something pretty weird happened.
I hacked a tower for deception, which resulted in mind-controlling a snek in a pod across the map.
On the same turn, my shinobi activated a second pod.
This pod had a drone, which I shut down via hacking with my specialist.
Funnily enough, for some unknown reason, this also resulted in mind-controlling of the gunner in the second pod.

**Comment by copyrite** [comment] 2023-12-23 17:09
Duplicate of #1056

**Closed by copyrite** 2023-12-23 17:09 UTC
Labels: bug, duplicate
