### ISSUE TITLE
failed covert actions

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1073] opened 2020-06-27 06:14 UTC
provide the wrong message. The guy says the covert action was successful and i see the new staffing opportunities available message.  The engineer, correctly, does not show up once I leave the covert action screen, but the messages that appear are wrong.

**Comment by Grobobobo** [comment] 2020-09-23 10:12
Duplicate of #1018

**Closed by Grobobobo** 2020-09-23 10:12 UTC
