### ISSUE TITLE
Alpha 5 - Blademaster can be parried by Mutons

### ISSUE THREAD

**Issue by rrnwang** [long-war-2/lwotc#372] opened 2019-07-28 06:34 UTC
In Alpha 4, and in Vanilla, a shinobi (or ranger) with blademaster can hit a melee strike on mutons. Since Alpha 5, the Mutons are able to parry the melee strike even when the attacker has blademaster. This does not affect blade storm.

**Comment by MiserablePileOfBugs** [comment] 2019-07-30 09:28
From what I remember, melee attacks on Mutons never worked 100% of the time even with Blademaster.

**Comment by Flouid** [comment] 2019-07-30 12:27
> From what I remember, melee attacks on Mutons never worked 100% of the time even with Blademaster.
I believe this is correct, all blademaster should do is increase sword damage IIRC

**Comment by rrnwang** [comment] 2019-07-31 02:03
Really!? Man, was I just getting lucky every time with Alpha 4? Can someone possibly point me to the source code or config where that is set? This is a surprise to me because I remember it always working in Vanilla...

**Comment by PodliKirill** [comment] 2019-07-31 12:50
In Vanilla - probably. But in LW2 blademaster cannot 100% bypass Mutons parry. But parry can be "turned off" by disorient or burning.

**Comment by jmartinez989** [comment] 2019-07-31 14:23
I remember mutons counter attacking blademaster rangers in vanilla as well. Muton counter success rate is pretty high so OP must be getting super lucky. 

Blademaster only increases sword attack aim by 10% and also crits on sword attacks do more damage.

Closing this as this is working as intended.

**Closed by jmartinez989** 2019-07-31 14:23 UTC
