### ISSUE TITLE
Graphic/Visual Bug - Saved crates on supply mission disappears when lifting off

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#257] opened 2019-06-20 05:48 UTC
Greetings.

As of the latest build, I noticed that the crate disappears upon lifting off. (See screenshot)

![Inked20190619232127_1_LI](https://user-images.githubusercontent.com/44072125/59823916-eac18900-92ec-11e9-8376-1db170cb44cb.jpg)

Before the moment it lifts, it's perfectly visible, then vanished once the fulton starts appearing.
I hope this doesn't have anything to do with my specific graphic settings, so hoping to confirm with others on this.

Black Rose

**Comment by pledbrook** [comment] 2019-06-20 10:22
I know that another player doesn't see the ADVENT claw that picks up the crates for them. May be a similar issue. No idea why only some folks encounter these issues. Never seen them in my own games.

**Comment by yoshimo** [comment] 2019-06-20 10:41
For me the xcom crates don't immediately vanish, looks like a balloon gets inflated before they take off.
I can confirm the missing ADVENT claw though.

**Comment by Ankaridan** [comment] 2019-06-22 03:05
Also confirming missing ADVENT claw.

XCOM crates work fine for me.

**Comment by Aurelicornus** [comment] 2019-07-08 14:17
I confirm to have the same bugs, both Player and Advent recover crates missing completely of the animation (crane and baloon).

**Comment by teepee2345** [comment] 2019-11-24 14:09
Am encountering a similar issue, except the balloon appears for its animation. The crate doesn't

**Comment by pledbrook** [comment] 2021-06-06 16:06
Fixed by putting the mission assets into *LongWarOfTheChosen/Content/BaseGameMissionAssets*.

**Closed by pledbrook** 2021-06-06 16:06 UTC
