### ISSUE TITLE
Recruit rookies screen stats (and View soldiers screen stats)

### ISSUE THREAD

**Issue by Gabok25** [long-war-2/lwotc#745] opened 2019-11-16 17:07 UTC
LWOTC recruit menu currently doesn't show the rookies' stats, meaning one would have to hire them first to see their stats, in LW2 you could see their stats before recruiting them, additionally, the recruit screen would also display their psionic stat after building the Psi Lab.

I also noticed that LWOTC's View Soldiers screen shows all their stats except defense, LW2 shows their defense.

![XCom2_2019_11_16_12_13_18_393](https://user-images.githubusercontent.com/57839596/68996292-6ad52600-086e-11ea-8b5d-9bc4e634cbf0.jpg)
![XCom2_2019_11_16_12_14_52_349](https://user-images.githubusercontent.com/57839596/68996312-ac65d100-086e-11ea-992d-a6b05beb46ea.jpg)

**Comment by nightmaRok** [comment] 2019-11-23 08:47
Duplicate #438 
For now you can see defence in roster, press -Toggle Details- button

![001](https://user-images.githubusercontent.com/51829747/69476125-7c727c80-0dde-11ea-8c9e-8b606d12c82c.JPG)

Close #745

**Comment by Clibanarius** [comment] 2019-11-24 13:23
The Recruit Rookie screen could use that back. I know LW2 had rookies show their stats there before you recruited them.

**Comment by pledbrook** [comment] 2019-11-25 10:19
@nightmaRok You should have the ability to close the issue yourself.

Closing as duplicate of #438

**Closed by pledbrook** 2019-11-25 10:19 UTC
Labels: duplicate
