### ISSUE TITLE
Reproducible CTD calling evac

### ISSUE THREAD

**Issue by InfiniteOregano** [long-war-2/lwotc#65] opened 2019-04-07 16:12 UTC
[save_BUGGYTURN1.zip](https://github.com/pledbrook/lwotc/files/3051713/save_BUGGYTURN1.zip)

To reproduce crash:

1. use up both actions on Jane Kelly
2. use teamwork on Natalie Cox on Jane Kelly
3. have Jane Kelly call for evac

Tested:

- does not crash if evac is called on start of her turn
- location evac placed did not seem to matter

**Comment by pledbrook** [comment] 2019-04-07 17:05
I wonder if this has the same cause as #38. I hope so. Thanks for the report and save file. I'll take a look.

**Comment by pledbrook** [comment] 2019-04-07 18:01
Ugh. I managed to reproduce this once by simply moving to a blue tile with Jane Kelly and then throwing the evac flare. But since I tried to debug the issue, I haven't seen it again.

I may try again with the released version in case it fails more reliably. But then I may not be able to debug it :(

**Comment by InfiniteOregano** [comment] 2019-04-07 18:19
Tested a few more things, and evac as second action as Jane crashed it... so not related to teamwork as I first suspected then.

Interestingly, evac by Amy as second action did not CTD... but it did when Natalie did the same...

So I guess might be about who it's going to pick as active character when turn ends or something? idk...

**Comment by pledbrook** [comment] 2019-04-08 06:10
This is going to be very difficult to diagnose, that much I do know :smile: I'll see what I can do, but I'll probably prioritise fixing easier, more game-breaking stuff.

**Comment by pledbrook** [comment] 2019-04-09 17:09
Closing as duplicate of #38 (for which I'm hopeful I have a fix)

**Closed by pledbrook** 2019-04-09 17:09 UTC
Labels: blocker, bug, duplicate
