### ISSUE TITLE
Rescue soldier mission spawn again bug

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#290] opened 2019-06-29 11:44 UTC
I already do this mission. After next supply drop and refresh covert actions this mission spawn again.

![Rescue](https://user-images.githubusercontent.com/51829747/60383628-06125e00-9a7c-11e9-9578-cbfc53cffc1b.jpg)

![Rescue_1](https://user-images.githubusercontent.com/51829747/60383630-090d4e80-9a7c-11e9-9014-7d0279dcfb51.jpg)

[save_Rescue.zip](https://github.com/long-war-2/lwotc/files/3341812/save_Rescue.zip)

**Comment by pledbrook** [comment] 2019-07-09 19:13
I'll probably disable this for 1.6. I basically want to avoid having vanilla missions in the game until they're updated for LWOTC.

**Comment by pledbrook** [comment] 2019-08-19 15:16
If you have a save that's on the first rescue mission, that would be helpful. Unfortunately the one you've provided is currently crashing for me on load.

**Comment by nightmaRok** [comment] 2019-08-19 16:48
For now i have not any other saves for this issue

**Comment by pledbrook** [comment] 2019-08-19 17:09
I tried reproducing this, but couldn't. Perhaps it has something to do with the way the soldier is captured? I used a console command to force it.

**Comment by nightmaRok** [comment] 2019-08-20 07:15
In this save run i dont remember for sure, but i think 2 soldiers cuptured by chosen on mission and one on covert operation.

**Comment by nightmaRok** [comment] 2019-08-20 08:00
I test this save now, as i see chosen have not any captured soldiers.

[save_Rescue_2.zip](https://github.com/long-war-2/lwotc/files/3519290/save_Rescue_2.zip)

![2](https://user-images.githubusercontent.com/51829747/63328632-26062580-c339-11e9-8f4f-7485e4ad7e66.jpg)

Also after complete this mission i have 2 same soldiers

![1](https://user-images.githubusercontent.com/51829747/63328689-4209c700-c339-11e9-9674-171daf658ff0.jpg)

And also one thing, like in chosen stronghold assault you dont need infiltration time, with inf 0% enemy size not increased

![3](https://user-images.githubusercontent.com/51829747/63328850-8eed9d80-c339-11e9-8b50-3547dbf75dcb.jpg)
![4](https://user-images.githubusercontent.com/51829747/63328874-97de6f00-c339-11e9-91f2-8698f5d51b59.jpg)

**Comment by TheReigningKing** [comment] 2019-10-04 12:33
I've had this same exact issue.  I rescued the same soldier twice.

**Comment by mdger** [comment] 2019-12-16 20:11
This can definitely happen outside of LWOTC, too. I have the "[Always Recruit and Rescue](https://steamcommunity.com/sharedfiles/filedetails/?id=1136550654)" mod installed and I suspect it is causing this problem sometimes when loading or reloading a savegame.

**Comment by pledbrook** [comment] 2020-04-18 16:24
So this is probably due to the mission being in progress when a new "month" arrives and the covert actions are refreshed. Since they're refreshed before the soldier is rescued, the rescue mission appears again.

This will probably need a highlander fix.

**Comment by pledbrook** [comment] 2021-12-21 11:32
I'll close this as a known vanilla issue. I'm sure we'll eventually fix the bug where covert actions (like Recruit <Faction Soldier>) can be rolled while another one is in progress... honest!

**Closed by pledbrook** 2021-12-21 11:32 UTC
Labels: bug, highlander, has:save
