### ISSUE TITLE
Mind controlled units don't drop loot

### ISSUE THREAD

**Issue by Gabriel1601m** [long-war-2/lwotc#1078] opened 2020-07-10 03:56 UTC
Enemy units mind controlled by xcom don't drop corpses, loot, and experience when killed.

**Comment by bobjjones** [comment] 2020-07-31 21:32
This includes hacked units that die while they are hacked. However, if you load the game some time after the unit has died, a loot indicator with a 1 turn timer will be there. However, it won't count down, and the loot never expires. It is unclear if the phantom loot is collected at end of mission if "full salvage" is available.

**Comment by copyrite** [comment] 2023-12-21 20:11
Closing as duplicate of #1639.

**Closed by copyrite** 2023-12-21 20:11 UTC
