### ISSUE TITLE
Haywire Protocol: Values inconsistent

### ISSUE THREAD

**Issue by bmp2** [long-war-2/lwotc#619] opened 2019-09-27 02:04 UTC
The values shown on Haywire Protocol in the soldier's action menu are different than the values shown in the Hack screen.

https://imgur.com/a/ynpZJUs

**Comment by ansabalirai** [comment] 2019-09-27 03:15
There is a variance in the haywire rolls that LW2 adds which are not depicted by perfect information. The same thing exists in vanilla LW2 and is something people unfortunately lived with . Not sure if this could be fixed now that PI is integrated

**Comment by bmp2** [comment] 2019-09-27 12:49
I never used Perfect Information with LW2 so I never knew about the issue. Thanks for the explanation.
________________________________

**Comment by Grobobobo** [comment] 2019-11-24 17:11
Working as intended.

**Closed by Grobobobo** 2019-11-24 17:11 UTC
