### ISSUE TITLE
Templar Channel allows soldiers to pick up loot from a distance

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#742] opened 2019-11-14 06:43 UTC
Templar channel drops psi loot for the Templar. Stick a soldier that is not the Templar in this psi loot, then kill a unit that is carrying loot. The soldier in the psi loot will then pick up the dropped loot, even if the dropped loot is no where near the psi loot.

In the attached save, kill the drone (suggest combat protocol) and watch the shinobi pick up the loot from ~ 6 tiles away.
[save_Psi_teleported_pickup.zip](https://github.com/long-war-2/lwotc/files/3844954/save_Psi_teleported_pickup.zip)

**Comment by pledbrook** [comment] 2019-11-26 15:27
Duplicate of #182

**Closed by pledbrook** 2019-11-26 15:27 UTC
Labels: duplicate
