### ISSUE TITLE
Error displaying objectives

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#856] opened 2020-02-02 15:37 UTC
Hi,

Error displaying objectives, the letters overlap

![ObjetivosError](https://user-images.githubusercontent.com/56190157/73610657-12463700-45da-11ea-8035-e266d3f57e5c.png)

**Comment by copyrite** [comment] 2023-12-23 15:51
Duplicate of #354

**Closed by copyrite** 2023-12-23 15:51 UTC
Labels: bug, duplicate
