### ISSUE TITLE
Mod WOTC Extended Information! + Show more buff details don´t work

### ISSUE THREAD

**Issue by Pryda4ever** [long-war-2/lwotc#870] opened 2020-02-11 14:34 UTC
Hi people, i see in Installing Long War of the Chosen Mods than the LWOTC team recommended mods like Show more buff details, but when combined with WOCT Extended information! ( deactivating anything related to Aim Assist like they explain) first don´t work, don´t show nothing, 

Should I do something special to make them work together? Big Thanks!

**Comment by tjdouglas** [comment] 2020-02-11 17:45
Make sure that when you first launch the game you only have LWotC, the beta highlander, and the required mods enabled. 

After launching if you still have problems delete this folder, and relaunch the game

 \Documents\My Games\XCOM2 War of the Chosen\Config

[LWotC Troubleshooting Guide](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit)

**Comment by Pryda4ever** [comment] 2020-02-11 19:32
> 
> 
> Make sure that when you first launch the game you only have LWotC, the beta highlander, and the required mods enabled.
> 
> After launching if you still have problems delete this folder, and relaunch the game
> 
> \Documents\My Games\XCOM2 War of the Chosen\Config
> 
> [LWotC Troubleshooting Guide](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit)

Hi thanks but i don´t want to say that long war of the chosen going bad, i refer to pack Show more buff + with WOCT Extended information! first mod don´t show nothing, may be i need to edit some .ini, regards.

**Comment by tjdouglas** [comment] 2020-02-11 20:21
They should definitely work without ini edits. Unchecking the box next to Aim Assist should be all that is required. Have you tried validating your local files? It might be some leftovers from another mod.

**Comment by Pryda4ever** [comment] 2020-02-12 14:24
> 
> 
> They should definitely work without ini edits. Unchecking the box next to Aim Assist should be all that is required. Have you tried validating your local files? It might be some leftovers from another mod.

Tested 100% with this LWotC Troubleshooting Guide and nothing changed :S Maybe @pledbrook know some solution

**Comment by pledbrook** [comment] 2020-02-15 10:42
If you provide a save file, could perhaps take a look. Those mods definitely aren't incompatible with one another, so I don't know what the issue is. Do you have any other mods active that aren't in the required or recommended Steam collections?

**Comment by Pryda4ever** [comment] 2020-02-15 13:01
> 
> 
> If you provide a save file, could perhaps take a look. Those mods definitely aren't incompatible with one another, so I don't know what the issue is. Do you have any other mods active that aren't in the required or recommended Steam collections?

@pledbrook Hi Big Boss xDD, first thanks for bringing this mod to War Of The Chosen, here I have this save with all the mods that I use, anyway, I also checked it with only the recommended ones of this LWotC Troubleshooting Guide and it still didn't work

http://www.mediafire.com/file/mbeth5rjl9dglw8/save_Test_LW2_Of_The_Chosen_with_mods.rar/file

This is my mod list + WOTC Extended Information! (I didn't recommend WOTC Extended Information! on this list yet because it blocks Show more buff details) 

https://steamcommunity.com/sharedfiles/filedetails/?id=1989701973

**Comment by Pryda4ever** [comment] 2020-02-22 15:07
@pledbrook hi again any solution? thanks

**Comment by Grobobobo** [comment] 2022-01-17 16:42
This was already resolved in the discord server.

**Closed by Grobobobo** 2022-01-17 16:42 UTC
