### ISSUE TITLE
Chosen Avenger Defense made unwinnable (unable to plant X4)

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1465] opened 2021-10-24 21:48 UTC
CAD can be made unwinnable due to being unable to plant an X4 charge on the small tanks. Its been shown that if a unit destroys terrain too close to the tanks then the objective mark to plant disappears and thus making the mission impossible to complete. 
Here is what the objective looks like at the start of the mission
<img width="643" alt="CAD_Unbugged_Objective" src="https://user-images.githubusercontent.com/39199279/138614083-6aca08b6-9e54-4cc7-b0fe-e96828ce6488.png">
This is what it looks like when a pod scampered and destroyed a nearby tree
![Screenshot_2021-10-15_at_09 47 12](https://user-images.githubusercontent.com/39199279/138614109-d0bd9f97-2b75-4103-855f-a8ad9a04b0ab.png)
Which then results in the objective mark disappearing along with the ability to plant
<img width="1417" alt="Bugged_Avenger_Defence" src="https://user-images.githubusercontent.com/39199279/138614132-fdf35636-139e-4a3f-998f-f14e4cc82e35.png">

Here is a save file with the objective in a bugged state 
[save_Bugged_Avenger_Defence_copy.zip](https://github.com/long-war-2/lwotc/files/7406308/save_Bugged_Avenger_Defence_copy.zip)

**Comment by pledbrook** [comment] 2021-12-19 16:20
Duplicate of #1497

**Closed by pledbrook** 2021-12-19 16:20 UTC
