### ISSUE TITLE
Ambient music missing on some missions (and other music issues)

### ISSUE THREAD

**Issue by tacticalweapon1** [long-war-2/lwotc#1326] opened 2021-06-07 01:26 UTC
At the moment, some missions act very strange when it comes to the music. Jailbreak missions and smash and grab missions do not have ambient music and I am running into a weird issue on abandoned maps. Sometimes there will be no music, other times after a reload there is. Anyone else having this issue? Does this appear elsewhere?

**Comment by pledbrook** [comment] 2021-06-07 18:54
Duplicate of #338.

**Closed by pledbrook** 2021-06-07 18:54 UTC
Labels: duplicate

**Comment by pledbrook** [comment] 2021-06-07 20:43
Are you using beta 4?
