### ISSUE TITLE
CCS on Vanguard not working

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#885] opened 2020-02-19 19:25 UTC
Playing beta 2. Had vanguard on several occasions now as enemy and went into close range  at least 3 or 4 four times. CCS never triggered.

**Comment by pledbrook** [comment] 2020-02-19 19:28
Duplicate of #699

**Closed by pledbrook** 2020-02-19 19:28 UTC
Labels: duplicate

**Comment by McTrevor79** [comment] 2020-02-19 19:30
Sorry. I am on mobile. Didn't show me related issues.

**Comment by pledbrook** [comment] 2020-02-19 19:32
No worries. Also, GitHub no longer pops the suggestions up as you type as far as I can tell. They show a little link with, for example, "4 similar issues found" as its text.
